[package]
name = "pepe"
version = "0.3.1"
authors = ["Omar MHAIMDAT"]
edition = "2021"
rust-version = "1.85"
description = "HTTP load generator and performance testing tool"
readme = "README.md"
homepage = "https://github.com/omarmhaimdat/pepe"
repository = "https://github.com/omarmhaimdat/pepe"
keywords = ["testing", "performance", "benchmark", "stress", "utility"]
categories = ["command-line-utilities", "network-programming"]
license = "MIT"
exclude = ["assets/*"]

[dependencies]
clap = { version = "4.5.24", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
reqwest = { version = "0.12.12", default-features = false, features = [
    "json",
    "rustls-tls",
    "socks",
] }
hyper = "1.5.2"
futures = "0.3.17"
tokio-stream = "0.1"
ratatui = "0.29.0"
crossterm = "0.28.1"
indicatif = "0.18"
curl-parser = { git = "https://github.com/omarmhaimdat/curl-parser", rev = "415558b02aa5ce98fcbfb80841c5ff35562e762d", version = "0.5.5" }
gethostname = "1.0.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
axoupdater = "0.10.2"
semver = "1.0.28"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.release.package."*"]
opt-level = 3
debug = false
strip = true

[[bin]]
name = "pepe"
path = "src/main.rs"

# Profile used by `dist build` for release artifacts.
[profile.dist]
inherits = "release"
