//! `pepe completions`: the completion script for a shell, or installing it
//! and the man pages so that tab completion works in the next shell.
//!
//! The files are generated by `src/contrib.rs` and embedded here, so this
//! works however pepe was installed. The installers run it after installing,
//! and `pepe self-update` runs it again for the shells it was set up for.

use std::path::{Path, PathBuf};

use crate::cli::CompletionsArgs;

#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum Shell {
    Bash,
    Zsh,
    Fish,
    Powershell,
}

/// Marks the lines pepe adds to a shell's startup file, so they're added once
const MARKER: &str = "# pepe: tab completion (pepe completions --install)";

const MAN_PAGES: [(&str, &str); 5] = [
    ("pepe.1", include_str!("../contrib/man/pepe.1")),
    ("pepe-ramp.1", include_str!("../contrib/man/pepe-ramp.1")),
    ("pepe-api.1", include_str!("../contrib/man/pepe-api.1")),
    (
        "pepe-self-update.1",
        include_str!("../contrib/man/pepe-self-update.1"),
    ),
    (
        "pepe-completions.1",
        include_str!("../contrib/man/pepe-completions.1"),
    ),
];

impl Shell {
    pub const ALL: [Shell; 4] = [Shell::Bash, Shell::Zsh, Shell::Fish, Shell::Powershell];

    fn name(self) -> &'static str {
        match self {
            Shell::Bash => "bash",
            Shell::Zsh => "zsh",
            Shell::Fish => "fish",
            Shell::Powershell => "PowerShell",
        }
    }

    pub fn script(self) -> &'static str {
        match self {
            Shell::Bash => include_str!("../contrib/completions/pepe.bash"),
            Shell::Zsh => include_str!("../contrib/completions/_pepe"),
            Shell::Fish => include_str!("../contrib/completions/pepe.fish"),
            Shell::Powershell => include_str!("../contrib/completions/_pepe.ps1"),
        }
    }

    /// The shell a terminal opens, from `$SHELL`
    fn current() -> Option<Shell> {
        if cfg!(windows) {
            return Some(Shell::Powershell);
        }
        Self::from_path(&std::env::var("SHELL").ok()?)
    }

    /// The name clap knows the shell by
    pub fn arg(self) -> &'static str {
        match self {
            Shell::Bash => "bash",
            Shell::Zsh => "zsh",
            Shell::Fish => "fish",
            Shell::Powershell => "powershell",
        }
    }

    fn from_path(shell: &str) -> Option<Shell> {
        // Both separators: a Windows path may be looked at from anywhere
        match shell.rsplit(['/', '\\']).next()? {
            "bash" => Some(Shell::Bash),
            "zsh" => Some(Shell::Zsh),
            "fish" => Some(Shell::Fish),
            "pwsh" | "powershell" | "pwsh.exe" | "powershell.exe" => Some(Shell::Powershell),
            _ => None,
        }
    }
}

/// Where things go for one user
struct Dirs {
    home: PathBuf,
    /// `$XDG_DATA_HOME`, `~/.local/share` by default
    data: PathBuf,
    /// `$XDG_CONFIG_HOME`, `~/.config` by default
    config: PathBuf,
    /// Where zsh reads `.zshrc`: `$ZDOTDIR` or home
    zdotdir: PathBuf,
}

impl Dirs {
    fn detect() -> Option<Self> {
        let home =
            PathBuf::from(std::env::var_os("HOME").or_else(|| std::env::var_os("USERPROFILE"))?);
        let or = |var: &str, default: PathBuf| std::env::var_os(var).map_or(default, PathBuf::from);
        Some(Self {
            data: or("XDG_DATA_HOME", home.join(".local/share")),
            config: or("XDG_CONFIG_HOME", home.join(".config")),
            zdotdir: or("ZDOTDIR", home.clone()),
            home,
        })
    }

    /// `~/...` when a path is under home, for the report and startup files
    fn tilde(&self, path: &Path) -> String {
        match path.strip_prefix(&self.home) {
            Ok(rest) => format!("~/{}", rest.display()).replace('\\', "/"),
            Err(_) => path.display().to_string(),
        }
    }
}

/// What installing comes to: files to write, and lines a startup file needs
struct Plan {
    files: Vec<(PathBuf, &'static str)>,
    /// The startup file and the block to append, for shells that need one
    startup: Option<(PathBuf, String)>,
}

fn plan(shell: Shell, dirs: &Dirs) -> Plan {
    let mut files = Vec::new();
    let mut startup = None;
    match shell {
        Shell::Zsh => {
            let dir = dirs.data.join("zsh/site-functions");
            files.push((dir.join("_pepe"), shell.script()));
            // The directory must be on fpath before compinit runs; appended
            // to the end of .zshrc, compinit is run (again) once it is
            startup = Some((
                dirs.zdotdir.join(".zshrc"),
                format!(
                    "{MARKER}\nfpath=({} $fpath)\nautoload -Uz compinit && compinit\n",
                    dirs.tilde(&dir)
                ),
            ));
        }
        Shell::Bash => {
            let file = dirs.data.join("bash-completion/completions/pepe");
            files.push((file.clone(), shell.script()));
            let rc = if cfg!(target_os = "macos") {
                ".bash_profile"
            } else {
                ".bashrc"
            };
            let file = dirs.tilde(&file);
            startup = Some((
                dirs.home.join(rc),
                format!("{MARKER}\n[ -r {file} ] && source {file}\n"),
            ));
        }
        // fish loads everything in this directory by itself
        Shell::Fish => files.push((
            dirs.config.join("fish/completions/pepe.fish"),
            shell.script(),
        )),
        Shell::Powershell => {
            let dir = if cfg!(windows) {
                dirs.home.join("Documents/PowerShell")
            } else {
                dirs.config.join("powershell")
            };
            let file = dir.join("pepe-completions.ps1");
            files.push((file.clone(), shell.script()));
            startup = Some((
                dir.join("Microsoft.PowerShell_profile.ps1"),
                format!("{MARKER}\n. \"{}\"\n", file.display()),
            ));
        }
    }
    if !cfg!(windows) {
        // man finds ~/.local/share/man on its own when ~/.local/bin is on PATH
        let man1 = dirs.data.join("man/man1");
        files.extend(
            MAN_PAGES
                .iter()
                .map(|&(name, page)| (man1.join(name), page)),
        );
    }
    Plan { files, startup }
}

/// Carries the plan out, or says what it would do. Returns the report.
fn apply(plan: &Plan, dirs: &Dirs, dry_run: bool) -> std::io::Result<Vec<String>> {
    let mut report = Vec::new();
    let verb = |did: &str, would: &str| if dry_run { would } else { did }.to_string();
    for (path, content) in &plan.files {
        let current = std::fs::read_to_string(path).ok().as_deref() == Some(*content);
        if current {
            report.push(format!("  {} is current", dirs.tilde(path)));
            continue;
        }
        if !dry_run {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(path, content)?;
        }
        report.push(format!(
            "{} {}",
            verb("✔ wrote", "would write"),
            dirs.tilde(path)
        ));
    }
    if let Some((rc, block)) = &plan.startup {
        let existing = std::fs::read_to_string(rc).unwrap_or_default();
        if existing.contains(MARKER) {
            report.push(format!("  {} is already set up", dirs.tilde(rc)));
        } else {
            if !dry_run {
                if let Some(parent) = rc.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                let sep = if existing.is_empty() || existing.ends_with('\n') {
                    "\n"
                } else {
                    "\n\n"
                };
                std::fs::write(rc, format!("{existing}{sep}{block}"))?;
            }
            report.push(format!(
                "{} {} lines to {}:",
                verb("✔ added", "would add"),
                block.lines().count(),
                dirs.tilde(rc)
            ));
            report.extend(block.lines().map(|l| format!("    {l}")));
        }
    }
    Ok(report)
}

/// `pepe completions`: print the script, or install it
pub fn run(args: &CompletionsArgs) -> Result<(), Box<dyn std::error::Error>> {
    let shell = match args.shell.or_else(Shell::current) {
        Some(shell) => shell,
        None => {
            let from = std::env::var("SHELL").unwrap_or_default();
            return Err(format!(
                "which shell? $SHELL is {from:?}, which pepe doesn't know; \
                 say one: pepe completions bash|zsh|fish|powershell"
            )
            .into());
        }
    };
    if !args.install {
        print!("{}", shell.script());
        return Ok(());
    }
    let dirs = Dirs::detect().ok_or("can't tell where home is: $HOME isn't set")?;
    let report = apply(&plan(shell, &dirs), &dirs, args.dry_run)?;
    let what = if args.dry_run {
        "would set up"
    } else {
        "set up"
    };
    println!(
        "{what} tab completion for {} and the man pages",
        shell.name()
    );
    for line in report {
        println!("{line}");
    }
    if !args.dry_run {
        println!(
            "{}",
            match shell {
                Shell::Fish => "new fish shells pick it up; `pepe --<tab>` to try",
                Shell::Powershell => "open a new PowerShell window and try `pepe --<tab>`",
                Shell::Zsh => "open a new shell, or run `exec zsh`, and try `pepe --<tab>`",
                Shell::Bash => "open a new shell, or run `exec bash`, and try `pepe --<tab>`",
            }
        );
    }
    Ok(())
}

/// The shells this user set completions up for: the ones with the
/// completion file where `--install` puts it
pub fn installed_shells() -> Vec<Shell> {
    let Some(dirs) = Dirs::detect() else {
        return Vec::new();
    };
    Shell::ALL
        .into_iter()
        .filter(|&shell| plan(shell, &dirs).files[0].0.exists())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dirs(home: &Path) -> Dirs {
        Dirs {
            home: home.to_path_buf(),
            data: home.join(".local/share"),
            config: home.join(".config"),
            zdotdir: home.to_path_buf(),
        }
    }

    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("pepe-completions-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn shells_are_told_apart_by_the_binary_name() {
        assert_eq!(Shell::from_path("/bin/zsh"), Some(Shell::Zsh));
        assert_eq!(
            Shell::from_path("/opt/homebrew/bin/bash"),
            Some(Shell::Bash)
        );
        assert_eq!(Shell::from_path("/usr/local/bin/fish"), Some(Shell::Fish));
        assert_eq!(
            Shell::from_path("C:\\\\Program Files\\\\PowerShell\\\\7\\\\pwsh.exe"),
            Some(Shell::Powershell)
        );
        assert_eq!(Shell::from_path("/bin/tcsh"), None);
        assert_eq!(Shell::from_path(""), None);
    }

    #[test]
    fn every_shell_has_a_script_with_the_command_in_it() {
        for shell in Shell::ALL {
            assert!(
                shell.script().contains("completions"),
                "{shell:?} knows its own subcommand"
            );
            assert!(shell.script().contains("self-update"));
        }
    }

    #[test]
    fn installing_writes_the_files_once_and_says_so() {
        let home = scratch("zsh");
        let dirs = dirs(&home);
        let plan = plan(Shell::Zsh, &dirs);

        let dry = apply(&plan, &dirs, true).unwrap();
        assert!(dry
            .iter()
            .any(|l| l.starts_with("would write ~/.local/share/zsh/site-functions/_pepe")));
        assert!(!home.join(".zshrc").exists(), "a dry run touches nothing");

        let first = apply(&plan, &dirs, false).unwrap();
        assert!(first
            .iter()
            .any(|l| l == "✔ wrote ~/.local/share/zsh/site-functions/_pepe"));
        assert!(first
            .iter()
            .any(|l| l.contains("added 3 lines to ~/.zshrc")));
        let zshrc = std::fs::read_to_string(home.join(".zshrc")).unwrap();
        assert!(zshrc.contains(MARKER));
        assert!(zshrc.contains("fpath=(~/.local/share/zsh/site-functions $fpath)"));
        assert!(zshrc.contains("compinit"));
        assert_eq!(
            std::fs::read_to_string(home.join(".local/share/zsh/site-functions/_pepe")).unwrap(),
            Shell::Zsh.script()
        );
        assert!(home.join(".local/share/man/man1/pepe.1").exists());

        let again = apply(&plan, &dirs, false).unwrap();
        assert!(
            again
                .iter()
                .all(|l| l.contains("is current") || l.contains("already set up")),
            "{again:?}"
        );
        assert_eq!(
            zshrc,
            std::fs::read_to_string(home.join(".zshrc")).unwrap(),
            "nothing appended twice"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn startup_lines_are_appended_after_what_is_there() {
        let home = scratch("bash");
        let dirs = dirs(&home);
        let rc = if cfg!(target_os = "macos") {
            ".bash_profile"
        } else {
            ".bashrc"
        };
        std::fs::write(home.join(rc), "export EDITOR=vim").unwrap();
        apply(&plan(Shell::Bash, &dirs), &dirs, false).unwrap();
        let text = std::fs::read_to_string(home.join(rc)).unwrap();
        assert!(text.starts_with("export EDITOR=vim\n\n# pepe"), "{text:?}");
        assert!(text.contains("source ~/.local/share/bash-completion/completions/pepe"));
        // fish needs no startup line at all
        let fish = plan(Shell::Fish, &dirs);
        assert!(fish.startup.is_none());
        assert!(fish.files[0]
            .0
            .ends_with(".config/fish/completions/pepe.fish"));
        let _ = std::fs::remove_dir_all(&home);
    }
}
