name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: [
          x86_64-unknown-linux-gnu,
          aarch64-unknown-linux-gnu,
          x86_64-apple-darwin,
          aarch64-apple-darwin
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential devscripts debhelper cargo

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc
          xcode-select --install || true

      - name: Build CLI Project
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Debian (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          mkdir -p pepe/debian
          echo "Source: pepe
          Section: utils
          Priority: optional
          Maintainer: Omar MHAIMDAT <omarmhaimdat@gmail.com>
          Build-Depends: debhelper (>= 9), build-essential
          Standards-Version: 3.9.6
          Homepage: https://github.com/omarmhaimdat/pepe

          Package: pepe
          Architecture: amd64
          Description: HTTP load generator
          Pepe is a command-line HTTP load generator." > pepe/debian/control

          echo "#!/usr/bin/make -f
          %:
          \tdh \$@" > pepe/debian/rules

          echo "pepe (0.1.0) unstable; urgency=low
            * Initial release
           -- Omar MHAIMDAT <omarmhaimdat@gmail.com>  $(date -R)" > pepe/debian/changelog

          chmod +x pepe/debian/rules
          dpkg-buildpackage -us -uc

      - name: Package Homebrew (macOS)
        if: matrix.os == 'macos-latest' && matrix.target == 'x86_64-apple-darwin'
        run: |
          mkdir -p dist
          tar -czvf dist/pepe-macos.tar.gz -C target/${{ matrix.target }}/release pepe

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pepe-${{ matrix.target }}
          path: |
            ../pepe_*.deb
            dist/pepe-macos.tar.gz

  release:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4

      - name: Push to APT Repository
        run: |
          # Your script for uploading .deb to APT repository
          echo "Uploading .deb to APT repo..."

      - name: Push to Homebrew
        run: |
          git clone https://github.com/omarmhaimdat/homebrew-pepe.git
          tar -xzvf dist/pepe-macos.tar.gz -C homebrew-pepe/bin
          cd homebrew-pepe
          git add .
          git commit -m "Release $(date +%Y-%m-%d)"
          git push
